version: '3.8'
services:
  server:
    build: ./packages/server/
    container_name: 'mango-i18n-system-server'
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./packages/server/database:/home/app/server/database
    ports:
      - '5006:8080'
    expose:
      - '8080'
    restart: always
    networks:
      - backend

  client:
    build: ./packages/client/
    container_name: 'mango-i18n-system-client'
    depends_on:
      - server
    ports:
      - '5005:80'
    restart: always
    networks:
      - backend

networks:
  backend:
    driver: bridge
